apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: us-east4-docker.pkg.dev/qwiklabs-gcp-02-0f000e0c6ad2/my-repository/hello-app:v2.0
        ports:
        - containerPort: 8080
